---
title: "Regards"
author: "JB MANCHON"
date: "8 août 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(plyr)
library(car)
library(lsr)
library(sjstats)
library(ggplot2)
setwd("C:\\Users\\jmanchon\\Documents\\Donnees\\iMotions")
data <- read.csv("results_full_oculo.csv", encoding = 'UTF-8')
```


```{r data, include=FALSE}
data <- cbind(data, data.frame("NB_RETRO_ROUTE" = data$NB_RETRO+data$NB_ROUTE, "TPS_RETRO_ROUTE" = data$TPS_RETRO+data$TPS_ROUTE, "FRQ_RETRO_ROUTE" = data$FRQ_RETRO+data$FRQ_ROUTE))

CONF <- subset(data, GROUPE == "CONFIANTS")
MEF <- subset(data, GROUPE == "MEFIANTS")

# Pour les t-tests
CONF_TOT <- subset(CONF, TEMPS == "TOTAL")
CONF_P1 <- subset(CONF, TEMPS == "P1")
CONF_P2 <- subset(CONF, TEMPS == "P2")
CONF_P3 <- subset(CONF, TEMPS == "P3")
CONF_CU1 <- subset(CONF, TEMPS == "CU1")
CONF_CU2 <- subset(CONF, TEMPS == "CU2")

MEF_TOT <- subset(MEF, TEMPS == "TOTAL")
MEF_P1 <- subset(MEF, TEMPS == "P1")
MEF_P2 <- subset(MEF, TEMPS == "P2")
MEF_P3 <- subset(MEF, TEMPS == "P3")
MEF_CU1 <- subset(MEF, TEMPS == "CU1")
MEF_CU2 <- subset(MEF, TEMPS == "CU2")

# Pour les ANOVA
PERIODES <- subset(data, TEMPS == "P1" | TEMPS == "P2" | TEMPS == "P3")
CU <- subset(data, TEMPS == "CU1" | TEMPS == "CU2")

# Pour les graph
tmp <- PERIODES[, -(1:2)]
PERIODES_M <- data.frame("GROUPE" = c("MEFIANTS"), TEMPS = c("P1", "P2", "P3"))
PERIODES_M <- rbind(PERIODES_M, data.frame("GROUPE" = c("CONFIANTS"), TEMPS = c("P1", "P2", "P3")))
PERIODES_M_tmp <- colwise(mean)(tmp[1:20, ])
PERIODES_M_tmp <- rbind(PERIODES_M_tmp, colwise(mean)(tmp[21:40, ]))
PERIODES_M_tmp <- rbind(PERIODES_M_tmp, colwise(mean)(tmp[41:60, ]))
PERIODES_M_tmp <- rbind(PERIODES_M_tmp, colwise(mean)(tmp[61:78, ]))
PERIODES_M_tmp <- rbind(PERIODES_M_tmp, colwise(mean)(tmp[79:96, ]))
PERIODES_M_tmp <- rbind(PERIODES_M_tmp, colwise(mean)(tmp[97:114, ]))

PERIODES_M_tmp2 <- colwise(sd)(tmp[1:20, ])
PERIODES_M_tmp2 <- rbind(PERIODES_M_tmp2, colwise(sd)(tmp[21:40, ]))
PERIODES_M_tmp2 <- rbind(PERIODES_M_tmp2, colwise(sd)(tmp[41:60, ]))
PERIODES_M_tmp2 <- rbind(PERIODES_M_tmp2, colwise(sd)(tmp[61:78, ]))
PERIODES_M_tmp2 <- rbind(PERIODES_M_tmp2, colwise(sd)(tmp[79:96, ]))
PERIODES_M_tmp2 <- rbind(PERIODES_M_tmp2, colwise(sd)(tmp[97:114, ]))
colnames(PERIODES_M_tmp2) <- c("NB_FIXATION_sd", "NB_ROUTE_sd", "NB_RETRO_sd", "NB_AVB_sd", "NB_AUTRE_sd", "TPS_FIXATION_sd", "FRQ_FIXATION_sd", "TPS_ROUTE_sd", "FRQ_ROUTE_sd", "TPS_RETRO_sd", "FRQ_RETRO_sd", "TPS_AVB_sd", "FRQ_AVB_sd", "TPS_AUTRE_sd", "FRQ_AUTRE_sd", "NB_RETRO_ROUTE_sd", "TPS_RETRO_ROUTE_sd", "FRQ_RETRO_ROUTE_sd")

PERIODES_M <- cbind(PERIODES_M, PERIODES_M_tmp, PERIODES_M_tmp2)
rm(tmp, PERIODES_M_tmp, PERIODES_M_tmp2)

tmp <- CU[, -(1:2)]
CU_M <- data.frame("GROUPE" = c("MEFIANTS"), TEMPS = c("CU1", "CU2"))
CU_M <- rbind(CU_M, data.frame("GROUPE" = c("CONFIANTS"), TEMPS = c("CU1", "CU2")))
CU_M_tmp <- colwise(mean)(tmp[1:20,])
CU_M_tmp <- rbind(CU_M_tmp, colwise(mean)(tmp[21:40,]))
CU_M_tmp <- rbind(CU_M_tmp, colwise(mean)(tmp[41:58,]))
CU_M_tmp <- rbind(CU_M_tmp, colwise(mean)(tmp[69:76,]))

CU_M_tmp2 <- colwise(sd)(tmp[1:20,])
CU_M_tmp2 <- rbind(CU_M_tmp2, colwise(sd)(tmp[21:40,]))
CU_M_tmp2 <- rbind(CU_M_tmp2, colwise(sd)(tmp[41:58,]))
CU_M_tmp2 <- rbind(CU_M_tmp2, colwise(sd)(tmp[69:76,]))
colnames(CU_M_tmp2) <- c("NB_FIXATION_sd", "NB_ROUTE_sd", "NB_RETRO_sd", "NB_AVB_sd", "NB_AUTRE_sd", "TPS_FIXATION_sd", "FRQ_FIXATION_sd", "TPS_ROUTE_sd", "FRQ_ROUTE_sd", "TPS_RETRO_sd", "FRQ_RETRO_sd", "TPS_AVB_sd", "FRQ_AVB_sd", "TPS_AUTRE_sd", "FRQ_AUTRE_sd", "NB_RETRO_ROUTE_sd", "TPS_RETRO_ROUTE_sd", "FRQ_RETRO_ROUTE_sd")

CU_M <- cbind(CU_M, CU_M_tmp, CU_M_tmp2)
rm(tmp, CU_M_tmp, CU_M_tmp2)
```


################ NOMBRE DE REGARDS

ANOVA ET T-TEST NOMBRE DE REGARDS PÉRIODES
```{r}
NB_TOT_AOV <- Anova(lm(NB_FIXATION~TEMPS*GROUPE, data = PERIODES), type = 2, white.adjust=TRUE)
NB_TOT_AOV_ST <- anova_stats(Anova(lm(NB_FIXATION~TEMPS*GROUPE, data = PERIODES), type = 2))
NB_TOT_AOV
NB_TOT_AOV_ST

ggplot(PERIODES_M) + aes(x = TEMPS, y = NB_FIXATION, group= GROUPE, col = GROUPE, ymin = 0) + 
  geom_line(position=position_dodge(0.1)) + 
  geom_point(position=position_dodge(0.1)) +
  geom_errorbar(aes(ymin = NB_FIXATION - NB_FIXATION_sd, ymax = NB_FIXATION + NB_FIXATION_sd), 
                width = 0.1, position=position_dodge(0.1)) +
  ggtitle("Nombre de regards total") +
  labs(x = "Période", y = "Nombre de regards", col = "Groupe") +
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_TOT$NB_FIXATION, MEF_TOT$NB_FIXATION, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_TOT$NB_FIXATION, MEF_TOT$NB_FIXATION)))
t.test(CONF_P1$NB_FIXATION, MEF_P1$NB_FIXATION, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$NB_FIXATION, MEF_P1$NB_FIXATION)))
t.test(CONF_P2$NB_FIXATION, MEF_P2$NB_FIXATION, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$NB_FIXATION, MEF_P2$NB_FIXATION)))
t.test(CONF_P3$NB_FIXATION, MEF_P3$NB_FIXATION, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P3$NB_FIXATION, MEF_P3$NB_FIXATION)))

t.test(CONF_P1$NB_FIXATION, CONF_P2$NB_FIXATION, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$NB_FIXATION, CONF_P2$NB_FIXATION, method = "paired")))
t.test(CONF_P2$NB_FIXATION, CONF_P3$NB_FIXATION, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$NB_FIXATION, CONF_P3$NB_FIXATION, method = "paired")))
t.test(MEF_P1$NB_FIXATION, MEF_P2$NB_FIXATION, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P1$NB_FIXATION, MEF_P2$NB_FIXATION, method = "paired")))
t.test(MEF_P2$NB_FIXATION, MEF_P3$NB_FIXATION, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P2$NB_FIXATION, MEF_P3$NB_FIXATION, method = "paired")))

NB_ROUTE_AOV <- Anova(lm(NB_ROUTE~TEMPS*GROUPE, data = PERIODES), type = 2, white.adjust=TRUE)
NB_ROUTE_AOV_ST <- anova_stats(Anova(lm(NB_ROUTE~TEMPS*GROUPE, data = PERIODES), type = 2))
NB_ROUTE_AOV
NB_ROUTE_AOV_ST

ggplot(PERIODES_M) + aes(x = TEMPS, y = NB_ROUTE, group= GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=NB_ROUTE-NB_ROUTE_sd, ymax=NB_ROUTE+NB_ROUTE_sd), width=0.1, position=position_dodge(0.1)) +
  ggtitle("Nombre de regards vers la route") + 
  labs(x = "Période", y = "Nombre de regards", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_TOT$NB_ROUTE, MEF_TOT$NB_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_TOT$NB_ROUTE, MEF_TOT$NB_ROUTE)))
t.test(CONF_P1$NB_ROUTE, MEF_P1$NB_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$NB_ROUTE, MEF_P1$NB_ROUTE)))
t.test(CONF_P2$NB_ROUTE, MEF_P2$NB_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$NB_ROUTE, MEF_P2$NB_ROUTE)))
t.test(CONF_P3$NB_ROUTE, MEF_P3$NB_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P3$NB_ROUTE, MEF_P3$NB_ROUTE)))

t.test(CONF_P1$NB_ROUTE, CONF_P2$NB_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$NB_ROUTE, CONF_P2$NB_ROUTE, method = "paired")))
t.test(CONF_P2$NB_ROUTE, CONF_P3$NB_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$NB_ROUTE, CONF_P3$NB_ROUTE, method = "paired")))
t.test(MEF_P1$NB_ROUTE, MEF_P2$NB_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P1$NB_ROUTE, MEF_P2$NB_ROUTE, method = "paired")))
t.test(MEF_P2$NB_ROUTE, MEF_P3$NB_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P2$NB_ROUTE, MEF_P3$NB_ROUTE, method = "paired")))

NB_RETRO_AOV <- Anova(lm(NB_RETRO~TEMPS*GROUPE, data = PERIODES), type = 2, white.adjust=TRUE)
NB_RETRO_AOV_ST <- anova_stats(Anova(lm(NB_RETRO~TEMPS*GROUPE, data = PERIODES), type = 2))
NB_RETRO_AOV
NB_RETRO_AOV_ST

ggplot(PERIODES_M) + aes(x = TEMPS, y = NB_RETRO, group= GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=NB_RETRO-NB_RETRO_sd, ymax=NB_RETRO+NB_RETRO_sd), width=0.1, position=position_dodge(0.1)) +
  ggtitle("Nombre de regards vers les rétroviseurs") + 
  labs(x = "Période", y = "Nombre de regards", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_TOT$NB_RETRO, MEF_TOT$NB_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_TOT$NB_RETRO, MEF_TOT$NB_RETRO)))
t.test(CONF_P1$NB_RETRO, MEF_P1$NB_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$NB_RETRO, MEF_P1$NB_RETRO)))
t.test(CONF_P2$NB_RETRO, MEF_P2$NB_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$NB_RETRO, MEF_P2$NB_RETRO)))
t.test(CONF_P3$NB_RETRO, MEF_P3$NB_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P3$NB_RETRO, MEF_P3$NB_RETRO)))

t.test(CONF_P1$NB_RETRO, CONF_P2$NB_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$NB_RETRO, CONF_P2$NB_RETRO, method = "paired")))
t.test(CONF_P2$NB_RETRO, CONF_P3$NB_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$NB_RETRO, CONF_P3$NB_RETRO, method = "paired")))
t.test(MEF_P1$NB_RETRO, MEF_P2$NB_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P1$NB_RETRO, MEF_P2$NB_RETRO, method = "paired")))
t.test(MEF_P2$NB_RETRO, MEF_P3$NB_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P2$NB_RETRO, MEF_P3$NB_RETRO, method = "paired")))


NB_RETRO_ROUTE_AOV <- Anova(lm(NB_RETRO_ROUTE~TEMPS*GROUPE, data = PERIODES), type = 2, white.adjust=TRUE)
NB_RETRO_ROUTE_AOV_ST <- anova_stats(Anova(lm(NB_RETRO_ROUTE~TEMPS*GROUPE, data = PERIODES), type = 2))
NB_RETRO_ROUTE_AOV
NB_RETRO_ROUTE_AOV_ST

ggplot(PERIODES_M) + 
  geom_line(aes(x = TEMPS, y = NB_RETRO_ROUTE, group= GROUPE, col = GROUPE, linetype = "dashed"), position=position_dodge(0.1)) + 
    geom_line(aes(x = TEMPS, y = NB_AVB, group= GROUPE, col = GROUPE, linetype = "solid"), position=position_dodge(0.2)) + 
  scale_linetype_discrete(name = "Données", labels = c("Route/Rétro", "AVB")) +
  geom_point(aes(x = TEMPS, y = NB_RETRO_ROUTE, group= GROUPE, col = GROUPE), position=position_dodge(0.1)) + geom_point(aes(x = TEMPS, y = NB_AVB, group= GROUPE, col = GROUPE), position=position_dodge(0.2)) +
  geom_errorbar(aes(x = TEMPS, y = NB_RETRO_ROUTE, group= GROUPE, col = GROUPE, ymin=NB_RETRO_ROUTE-NB_RETRO_ROUTE_sd, ymax=NB_RETRO_ROUTE+NB_RETRO_ROUTE_sd), width=0.1, position=position_dodge(0.1)) +
  geom_errorbar(aes(x = TEMPS, y = NB_RETRO_ROUTE, group= GROUPE, col = GROUPE, ymin=NB_AVB-NB_AVB_sd, ymax=NB_AVB+NB_AVB_sd), width=0.1, position=position_dodge(0.2)) + 
  ggtitle("Nombre de regards vers la route\n& les rétroviseurs vs vers l'AVB") + 
  labs(x = "Période", y = "Nombre de regards", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_TOT$NB_RETRO_ROUTE, MEF_TOT$NB_RETRO_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_TOT$NB_RETRO_ROUTE, MEF_TOT$NB_RETRO_ROUTE)))
t.test(CONF_P1$NB_RETRO_ROUTE, MEF_P1$NB_RETRO_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$NB_RETRO_ROUTE, MEF_P1$NB_RETRO_ROUTE)))
t.test(CONF_P2$NB_RETRO_ROUTE, MEF_P2$NB_RETRO_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$NB_RETRO_ROUTE, MEF_P2$NB_RETRO_ROUTE)))
t.test(CONF_P3$NB_RETRO_ROUTE, MEF_P3$NB_RETRO_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P3$NB_RETRO_ROUTE, MEF_P3$NB_RETRO_ROUTE)))

t.test(CONF_P1$NB_RETRO_ROUTE, CONF_P2$NB_RETRO_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$NB_RETRO_ROUTE, CONF_P2$NB_RETRO_ROUTE, method = "paired")))
t.test(CONF_P2$NB_RETRO_ROUTE, CONF_P3$NB_RETRO_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$NB_RETRO_ROUTE, CONF_P3$NB_RETRO_ROUTE, method = "paired")))
t.test(MEF_P1$NB_RETRO_ROUTE, MEF_P2$NB_RETRO_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P1$NB_RETRO_ROUTE, MEF_P2$NB_RETRO_ROUTE, method = "paired")))
t.test(MEF_P2$NB_RETRO_ROUTE, MEF_P3$NB_RETRO_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P2$NB_RETRO_ROUTE, MEF_P3$NB_RETRO_ROUTE, method = "paired")))


NB_AVB_AOV <- Anova(lm(NB_AVB~TEMPS*GROUPE, data = PERIODES), type = 2, white.adjust=TRUE)
NB_AVB_AOV_ST <- anova_stats(Anova(lm(NB_AVB~TEMPS*GROUPE, data = PERIODES), type = 2))
NB_AVB_AOV
NB_AVB_AOV_ST

ggplot(PERIODES_M) + aes(x = TEMPS, y = NB_AVB, group= GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=NB_AVB-NB_AVB_sd, ymax=NB_AVB+NB_AVB_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Nombre de regards vers l'AVB") + 
  labs(x = "Période", y = "Nombre de regards", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_TOT$NB_AVB, MEF_TOT$NB_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_TOT$NB_AVB, MEF_TOT$NB_AVB)))
t.test(CONF_P1$NB_AVB, MEF_P1$NB_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$NB_AVB, MEF_P1$NB_AVB)))
t.test(CONF_P2$NB_AVB, MEF_P2$NB_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$NB_AVB, MEF_P2$NB_AVB)))
t.test(CONF_P3$NB_AVB, MEF_P3$NB_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P3$NB_AVB, MEF_P3$NB_AVB)))

t.test(CONF_P1$NB_AVB, CONF_P2$NB_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$NB_AVB, CONF_P2$NB_AVB, method = "paired")))
t.test(CONF_P2$NB_AVB, CONF_P3$NB_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$NB_AVB, CONF_P3$NB_AVB, method = "paired")))
t.test(MEF_P1$NB_AVB, MEF_P2$NB_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P1$NB_AVB, MEF_P2$NB_AVB, method = "paired")))
t.test(MEF_P2$NB_AVB, MEF_P3$NB_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P2$NB_AVB, MEF_P3$NB_AVB, method = "paired")))

NB_AUTRE_AOV <- Anova(lm(NB_AUTRE~TEMPS*GROUPE, data = PERIODES), type = 2, white.adjust=TRUE)
NB_AUTRE_AOV_ST <- anova_stats(Anova(lm(NB_AUTRE~TEMPS*GROUPE, data = PERIODES), type = 2))
NB_AUTRE_AOV
NB_AUTRE_AOV_ST

ggplot(PERIODES_M) + aes(x = TEMPS, y = NB_AUTRE, group= GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=NB_AUTRE-NB_AUTRE_sd, ymax=NB_AUTRE+NB_AUTRE_sd), width=0.1, position=position_dodge(0.1)) +
  ggtitle("Nombre de regards vers une autre zone") + 
  labs(x = "Période", y = "Nombre de regards", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_TOT$NB_AUTRE, MEF_TOT$NB_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_TOT$NB_AUTRE, MEF_TOT$NB_AUTRE)))
t.test(CONF_P1$NB_AUTRE, MEF_P1$NB_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$NB_AUTRE, MEF_P1$NB_AUTRE)))
t.test(CONF_P2$NB_AUTRE, MEF_P2$NB_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$NB_AUTRE, MEF_P2$NB_AUTRE)))
t.test(CONF_P3$NB_AUTRE, MEF_P3$NB_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P3$NB_AUTRE, MEF_P3$NB_AUTRE)))

t.test(CONF_P1$NB_AUTRE, CONF_P2$NB_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$NB_AUTRE, CONF_P2$NB_AUTRE, method = "paired")))
t.test(CONF_P2$NB_AUTRE, CONF_P3$NB_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$NB_AUTRE, CONF_P3$NB_AUTRE, method = "paired")))
t.test(MEF_P1$NB_AUTRE, MEF_P2$NB_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P1$NB_AUTRE, MEF_P2$NB_AUTRE, method = "paired")))
t.test(MEF_P2$NB_AUTRE, MEF_P3$NB_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P2$NB_AUTRE, MEF_P3$NB_AUTRE, method = "paired")))
```

ANOVA ET T-TEST NOMBRE DE REGARDS CU
```{r}
NB_TOT_AOV <- Anova(lm(NB_FIXATION~TEMPS*GROUPE, data = CU), type = 2, white.adjust=TRUE)
NB_TOT_AOV_ST <- anova_stats(Anova(lm(NB_FIXATION~TEMPS*GROUPE, data = CU), type = 2))
NB_TOT_AOV
NB_TOT_AOV_ST

ggplot(CU_M) + aes(x = TEMPS, y = NB_FIXATION, group= GROUPE, col = GROUPE, ymin = 0) + 
  geom_line(position=position_dodge(0.1)) + 
  geom_point(position=position_dodge(0.1)) +
  geom_errorbar(aes(ymin = NB_FIXATION - NB_FIXATION_sd, ymax = NB_FIXATION + NB_FIXATION_sd), 
                width = 0.1, position=position_dodge(0.1)) +
  ggtitle("Nombre de regards total") +
  labs(x = "Cas d'Usage", y = "Nombre de regards", col = "Groupe") +
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_CU1$NB_FIXATION, MEF_CU1$NB_FIXATION, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$NB_FIXATION, MEF_CU1$NB_FIXATION)))
t.test(CONF_CU2$NB_FIXATION, MEF_CU2$NB_FIXATION, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU2$NB_FIXATION, MEF_CU2$NB_FIXATION)))

t.test(CONF_CU1$NB_FIXATION, CONF_CU2$NB_FIXATION, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$NB_FIXATION, CONF_CU2$NB_FIXATION, method = "paired")))
t.test(MEF_CU1$NB_FIXATION, MEF_CU2$NB_FIXATION, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_CU1$NB_FIXATION, MEF_CU2$NB_FIXATION, method = "paired")))

NB_ROUTE_AOV <- Anova(lm(NB_ROUTE~TEMPS*GROUPE, data = CU), type = 2, white.adjust=TRUE)
NB_ROUTE_AOV_ST <- anova_stats(Anova(lm(NB_ROUTE~TEMPS*GROUPE, data = CU), type = 2))
NB_ROUTE_AOV
NB_ROUTE_AOV_ST

ggplot(CU_M) + aes(x = TEMPS, y = NB_ROUTE, group= GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=NB_ROUTE-NB_ROUTE_sd, ymax=NB_ROUTE+NB_ROUTE_sd), width=0.1, position=position_dodge(0.1)) + ggtitle("Nombre de regards vers la route") + 
  labs(x = "Cas d'Usage", y = "Nombre de regards", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_CU1$NB_ROUTE, MEF_CU1$NB_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$NB_ROUTE, MEF_CU1$NB_ROUTE)))
t.test(CONF_CU2$NB_ROUTE, MEF_CU2$NB_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU2$NB_ROUTE, MEF_CU2$NB_ROUTE)))

t.test(CONF_CU1$NB_ROUTE, CONF_CU2$NB_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$NB_ROUTE, CONF_CU2$NB_ROUTE, method = "paired")))
t.test(MEF_CU1$NB_ROUTE, MEF_CU2$NB_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_CU1$NB_ROUTE, MEF_CU2$NB_ROUTE, method = "paired")))

NB_RETRO_AOV <- Anova(lm(NB_RETRO~TEMPS*GROUPE, data = CU), type = 2, white.adjust=TRUE)
NB_RETRO_AOV_ST <- anova_stats(Anova(lm(NB_RETRO~TEMPS*GROUPE, data = CU), type = 2))
NB_RETRO_AOV
NB_RETRO_AOV_ST

ggplot(CU_M) + aes(x = TEMPS, y = NB_RETRO, group= GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=NB_RETRO-NB_RETRO_sd, ymax=NB_RETRO+NB_RETRO_sd), width=0.1, position=position_dodge(0.1)) + ggtitle("Nombre de regards vers les rétroviseurs") + 
  labs(x = "Cas d'Usage", y = "Nombre de regards", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_CU1$NB_RETRO, MEF_CU1$NB_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$NB_RETRO, MEF_CU1$NB_RETRO)))
t.test(CONF_CU2$NB_RETRO, MEF_CU2$NB_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU2$NB_RETRO, MEF_CU2$NB_RETRO)))

t.test(CONF_CU1$NB_RETRO, CONF_CU2$NB_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$NB_RETRO, CONF_CU2$NB_RETRO, method = "paired")))
t.test(MEF_CU1$NB_RETRO, MEF_CU2$NB_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_CU1$NB_RETRO, MEF_CU2$NB_RETRO, method = "paired")))

NB_AVB_AOV <- Anova(lm(NB_AVB~TEMPS*GROUPE, data = CU), type = 2, white.adjust=TRUE)
NB_AVB_AOV_ST <- anova_stats(Anova(lm(NB_AVB~TEMPS*GROUPE, data = CU), type = 2))
NB_AVB_AOV
NB_AVB_AOV_ST

ggplot(CU_M) + aes(x = TEMPS, y = NB_AVB, group= GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=NB_AVB-NB_AVB_sd, ymax=NB_AVB+NB_AVB_sd), width=0.1, position=position_dodge(0.1)) + ggtitle("Nombre de regards vers l'AVB") + 
  labs(x = "Cas d'Usage", y = "Nombre de regards", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_CU1$NB_AVB, MEF_CU1$NB_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$NB_AVB, MEF_CU1$NB_AVB)))
t.test(CONF_CU2$NB_AVB, MEF_CU2$NB_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU2$NB_AVB, MEF_CU2$NB_AVB)))

t.test(CONF_CU1$NB_AVB, CONF_CU2$NB_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$NB_AVB, CONF_CU2$NB_AVB, method = "paired")))
t.test(MEF_CU1$NB_AVB, MEF_CU2$NB_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_CU1$NB_AVB, MEF_CU2$NB_AVB, method = "paired")))

NB_AUTRE_AOV <- Anova(lm(NB_AUTRE~TEMPS*GROUPE, data = CU), type = 2, white.adjust=TRUE)
NB_AUTRE_AOV_ST <- anova_stats(Anova(lm(NB_AUTRE~TEMPS*GROUPE, data = CU), type = 2))
NB_AUTRE_AOV
NB_AUTRE_AOV_ST

ggplot(CU_M) + aes(x = TEMPS, y = NB_AUTRE, group= GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=NB_AUTRE-NB_AUTRE_sd, ymax=NB_AUTRE+NB_AUTRE_sd), width=0.1, position=position_dodge(0.1)) + ggtitle("Nombre de regards vers une autre zone") + 
  labs(x = "Cas d'Usage", y = "Nombre de regards", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_CU1$NB_AUTRE, MEF_CU1$NB_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$NB_AUTRE, MEF_CU1$NB_AUTRE)))
t.test(CONF_CU2$NB_AUTRE, MEF_CU2$NB_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU2$NB_AUTRE, MEF_CU2$NB_AUTRE)))

t.test(CONF_CU1$NB_AUTRE, CONF_CU2$NB_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$NB_AUTRE, CONF_CU2$NB_AUTRE, method = "paired")))
t.test(MEF_CU1$NB_AUTRE, MEF_CU2$NB_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_CU1$NB_AUTRE, MEF_CU2$NB_AUTRE, method = "paired")))
```


################ DURÉE DE REGARDS

ANOVA ET T-TEST DURÉE DES REGARDS PÉRIODES
```{r}
TPS_ROUTE_AOV <- Anova(lm(TPS_ROUTE~TEMPS*GROUPE, data = PERIODES), type = 2, white.adjust=TRUE)
TPS_ROUTE_AOV_ST <- anova_stats(Anova(lm(TPS_ROUTE~TEMPS*GROUPE, data = PERIODES), type = 2))
TPS_ROUTE_AOV
TPS_ROUTE_AOV_ST

ggplot(PERIODES_M) + aes(x = TEMPS, y = TPS_ROUTE, group = GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=TPS_ROUTE-TPS_ROUTE_sd, ymax=TPS_ROUTE+TPS_ROUTE_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Durée des regards vers la route") + 
  labs(x = "Période", y = "Durée des regards (sec)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_P1$TPS_ROUTE, MEF_P1$TPS_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$TPS_ROUTE, MEF_P1$TPS_ROUTE)))
t.test(CONF_P2$TPS_ROUTE, MEF_P2$TPS_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$TPS_ROUTE, MEF_P2$TPS_ROUTE)))
t.test(CONF_P3$TPS_ROUTE, MEF_P3$TPS_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P3$TPS_ROUTE, MEF_P3$TPS_ROUTE)))

t.test(CONF_P1$TPS_ROUTE, CONF_P2$TPS_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$TPS_ROUTE, CONF_P2$TPS_ROUTE, method = "paired")))
t.test(CONF_P2$TPS_ROUTE, CONF_P3$TPS_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$TPS_ROUTE, CONF_P3$TPS_ROUTE, method = "paired")))
t.test(MEF_P1$TPS_ROUTE, MEF_P2$TPS_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P1$TPS_ROUTE, MEF_P2$TPS_ROUTE, method = "paired")))
t.test(MEF_P2$TPS_ROUTE, MEF_P3$TPS_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P2$TPS_ROUTE, MEF_P3$TPS_ROUTE, method = "paired")))

TPS_RETRO_AOV <- Anova(lm(TPS_RETRO~TEMPS*GROUPE, data = PERIODES), type = 2, white.adjust=TRUE)
TPS_RETRO_AOV_ST <- anova_stats(Anova(lm(TPS_RETRO~TEMPS*GROUPE, data = PERIODES), type = 2))
TPS_RETRO_AOV
TPS_RETRO_AOV_ST

ggplot(PERIODES_M) + aes(x = TEMPS, y = TPS_RETRO, group = GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=TPS_RETRO-TPS_RETRO_sd, ymax=TPS_RETRO+TPS_RETRO_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Durée des regards vers les rétroviseurs") + 
  labs(x = "Période", y = "Durée des regards (sec)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_P1$TPS_RETRO, MEF_P1$TPS_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$TPS_RETRO, MEF_P1$TPS_RETRO)))
t.test(CONF_P2$TPS_RETRO, MEF_P2$TPS_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$TPS_RETRO, MEF_P2$TPS_RETRO)))
t.test(CONF_P3$TPS_RETRO, MEF_P3$TPS_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P3$TPS_RETRO, MEF_P3$TPS_RETRO)))

t.test(CONF_P1$TPS_RETRO, CONF_P2$TPS_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$TPS_RETRO, CONF_P2$TPS_RETRO, method = "paired")))
t.test(CONF_P2$TPS_RETRO, CONF_P3$TPS_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$TPS_RETRO, CONF_P3$TPS_RETRO, method = "paired")))
t.test(MEF_P1$TPS_RETRO, MEF_P2$TPS_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P1$TPS_RETRO, MEF_P2$TPS_RETRO, method = "paired")))
t.test(MEF_P2$TPS_RETRO, MEF_P3$TPS_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P2$TPS_RETRO, MEF_P3$TPS_RETRO, method = "paired")))

TPS_AVB_AOV <- Anova(lm(TPS_AVB~TEMPS*GROUPE, data = PERIODES), type = 2, white.adjust=TRUE)
TPS_AVB_AOV_ST <- anova_stats(Anova(lm(TPS_AVB~TEMPS*GROUPE, data = PERIODES), type = 2))
TPS_AVB_AOV
TPS_AVB_AOV_ST

ggplot(PERIODES_M) + aes(x = TEMPS, y = TPS_AVB, group = GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=TPS_AVB-TPS_AVB_sd, ymax=TPS_AVB+TPS_AVB_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Durée des regards vers l'AVB") + 
  labs(x = "Période", y = "Durée des regards (sec)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_P1$TPS_AVB, MEF_P1$TPS_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$TPS_AVB, MEF_P1$TPS_AVB)))
t.test(CONF_P2$TPS_AVB, MEF_P2$TPS_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$TPS_AVB, MEF_P2$TPS_AVB)))
t.test(CONF_P3$TPS_AVB, MEF_P3$TPS_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P3$TPS_AVB, MEF_P3$TPS_AVB)))

t.test(CONF_P1$TPS_AVB, CONF_P2$TPS_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$TPS_AVB, CONF_P2$TPS_AVB, method = "paired")))
t.test(CONF_P2$TPS_AVB, CONF_P3$TPS_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$TPS_AVB, CONF_P3$TPS_AVB, method = "paired")))
t.test(MEF_P1$TPS_AVB, MEF_P2$TPS_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P1$TPS_AVB, MEF_P2$TPS_AVB, method = "paired")))
t.test(MEF_P2$TPS_AVB, MEF_P3$TPS_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P2$TPS_AVB, MEF_P3$TPS_AVB, method = "paired")))

TPS_AUTRE_AOV <- Anova(lm(TPS_AUTRE~TEMPS*GROUPE, data = PERIODES), type = 2, white.adjust=TRUE)
TPS_AUTRE_AOV_ST <- anova_stats(Anova(lm(TPS_AUTRE~TEMPS*GROUPE, data = PERIODES), type = 2))
TPS_AUTRE_AOV
TPS_AUTRE_AOV_ST

ggplot(PERIODES_M) + aes(x = TEMPS, y = TPS_AUTRE, group = GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=TPS_AUTRE-TPS_AUTRE_sd, ymax=TPS_AUTRE+TPS_AUTRE_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Durée des regards vers une autre zone") + 
  labs(x = "Période", y = "Durée des regards (sec)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_P1$TPS_AUTRE, MEF_P1$TPS_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$TPS_AUTRE, MEF_P1$TPS_AUTRE)))
t.test(CONF_P2$TPS_AUTRE, MEF_P2$TPS_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$TPS_AUTRE, MEF_P2$TPS_AUTRE)))
t.test(CONF_P3$TPS_AUTRE, MEF_P3$TPS_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P3$TPS_AUTRE, MEF_P3$TPS_AUTRE)))

t.test(CONF_P1$TPS_AUTRE, CONF_P2$TPS_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$TPS_AUTRE, CONF_P2$TPS_AUTRE, method = "paired")))
t.test(CONF_P2$TPS_AUTRE, CONF_P3$TPS_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$TPS_AUTRE, CONF_P3$TPS_AUTRE, method = "paired")))
t.test(MEF_P1$TPS_AUTRE, MEF_P2$TPS_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P1$TPS_AUTRE, MEF_P2$TPS_AUTRE, method = "paired")))
t.test(MEF_P2$TPS_AUTRE, MEF_P3$TPS_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P2$TPS_AUTRE, MEF_P3$TPS_AUTRE, method = "paired")))
```

ANOVA ET T-TEST DURÉE DES REGARDS CU
```{r}
TPS_TOT_AOV <- Anova(lm(TPS_FIXATION~TEMPS*GROUPE, data = CU), type = 2, white.adjust=TRUE)
TPS_TOT_AOV_ST <- anova_stats(Anova(lm(TPS_FIXATION~TEMPS*GROUPE, data = CU), type = 2))
TPS_TOT_AOV
TPS_TOT_AOV_ST

ggplot(CU_M) + aes(x = TEMPS, y = TPS_FIXATION, group = GROUPE, col = GROUPE, ymin = 0) + 
  geom_line(position=position_dodge(0.1)) + 
  geom_point(position=position_dodge(0.1)) + 
  geom_errorbar(aes(ymin=TPS_FIXATION-TPS_FIXATION_sd, ymax=TPS_FIXATION+TPS_FIXATION_sd), 
                width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Durée des regards total") + 
  labs(x = "Cas d'Usage", y = "Durée des regards (sec)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_CU1$TPS_FIXATION, MEF_CU1$TPS_FIXATION, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$TPS_FIXATION, MEF_CU1$TPS_FIXATION)))
t.test(CONF_CU2$TPS_FIXATION, MEF_CU2$TPS_FIXATION, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU2$TPS_FIXATION, MEF_CU2$TPS_FIXATION)))

t.test(CONF_CU1$TPS_FIXATION, CONF_CU2$TPS_FIXATION, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$TPS_FIXATION, CONF_CU2$TPS_FIXATION, method = "paired")))
t.test(MEF_CU1$TPS_FIXATION, MEF_CU2$TPS_FIXATION, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_CU1$TPS_FIXATION, MEF_CU2$TPS_FIXATION, method = "paired")))

TPS_ROUTE_AOV <- Anova(lm(TPS_ROUTE~TEMPS*GROUPE, data = CU), type = 2, white.adjust=TRUE)
TPS_ROUTE_AOV_ST <- anova_stats(Anova(lm(TPS_ROUTE~TEMPS*GROUPE, data = CU), type = 2))
TPS_ROUTE_AOV
TPS_ROUTE_AOV_ST

ggplot(CU_M) + aes(x = TEMPS, y = TPS_ROUTE, group = GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=TPS_ROUTE-TPS_ROUTE_sd, ymax=TPS_ROUTE+TPS_ROUTE_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Durée des regards vers la route") + 
  labs(x = "Cas d'Usage", y = "Durée des regards (sec)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_CU1$TPS_ROUTE, MEF_CU1$TPS_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$TPS_ROUTE, MEF_CU1$TPS_ROUTE)))
t.test(CONF_CU2$TPS_ROUTE, MEF_CU2$TPS_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU2$TPS_ROUTE, MEF_CU2$TPS_ROUTE)))

t.test(CONF_CU1$TPS_ROUTE, CONF_CU2$TPS_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$TPS_ROUTE, CONF_CU2$TPS_ROUTE, method = "paired")))
t.test(MEF_CU1$TPS_ROUTE, MEF_CU2$TPS_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_CU1$TPS_ROUTE, MEF_CU2$TPS_ROUTE, method = "paired")))

TPS_RETRO_AOV <- Anova(lm(TPS_RETRO~TEMPS*GROUPE, data = CU), type = 2, white.adjust=TRUE)
TPS_RETRO_AOV_ST <- anova_stats(Anova(lm(TPS_RETRO~TEMPS*GROUPE, data = CU), type = 2))
TPS_RETRO_AOV
TPS_RETRO_AOV_ST

ggplot(CU_M) + aes(x = TEMPS, y = TPS_RETRO, group = GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=TPS_RETRO-TPS_RETRO_sd, ymax=TPS_RETRO+TPS_RETRO_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Durée des regards vers les rétroviseurs") + 
  labs(x = "Cas d'Usage", y = "Durée des regards (sec)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_CU1$TPS_RETRO, MEF_CU1$TPS_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$TPS_RETRO, MEF_CU1$TPS_RETRO)))
t.test(CONF_CU2$TPS_RETRO, MEF_CU2$TPS_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU2$TPS_RETRO, MEF_CU2$TPS_RETRO)))

t.test(CONF_CU1$TPS_RETRO, CONF_CU2$TPS_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$TPS_RETRO, CONF_CU2$TPS_RETRO, method = "paired")))
t.test(MEF_CU1$TPS_RETRO, MEF_CU2$TPS_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_CU1$TPS_RETRO, MEF_CU2$TPS_RETRO, method = "paired")))

TPS_AVB_AOV <- Anova(lm(TPS_AVB~TEMPS*GROUPE, data = CU), type = 2, white.adjust=TRUE)
TPS_AVB_AOV_ST <- anova_stats(Anova(lm(TPS_AVB~TEMPS*GROUPE, data = CU), type = 2))
TPS_AVB_AOV
TPS_AVB_AOV_ST

ggplot(CU_M) + aes(x = TEMPS, y = TPS_AVB, group = GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=TPS_AVB-TPS_AVB_sd, ymax=TPS_AVB+TPS_AVB_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Durée des regards vers l'AVB") + 
  labs(x = "Cas d'Usage", y = "Durée des regards (sec)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_CU1$TPS_AVB, MEF_CU1$TPS_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$TPS_AVB, MEF_CU1$TPS_AVB)))
t.test(CONF_CU2$TPS_AVB, MEF_CU2$TPS_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU2$TPS_AVB, MEF_CU2$TPS_AVB)))

t.test(CONF_CU1$TPS_AVB, CONF_CU2$TPS_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$TPS_AVB, CONF_CU2$TPS_AVB, method = "paired")))
t.test(MEF_CU1$TPS_AVB, MEF_CU2$TPS_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_CU1$TPS_AVB, MEF_CU2$TPS_AVB, method = "paired")))

TPS_AUTRE_AOV <- Anova(lm(TPS_AUTRE~TEMPS*GROUPE, data = CU), type = 2, white.adjust=TRUE)
TPS_AUTRE_AOV_ST <- anova_stats(Anova(lm(TPS_AUTRE~TEMPS*GROUPE, data = CU), type = 2))
TPS_AUTRE_AOV
TPS_AUTRE_AOV_ST

ggplot(CU_M) + aes(x = TEMPS, y = TPS_AUTRE, group = GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=TPS_AUTRE-TPS_AUTRE_sd, ymax=TPS_AUTRE+TPS_AUTRE_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Durée des regards vers une autre zone") + 
  labs(x = "Cas d'Usage", y = "Durée des regards (sec)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_CU1$TPS_AUTRE, MEF_CU1$TPS_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$TPS_AUTRE, MEF_CU1$TPS_AUTRE)))
t.test(CONF_CU2$TPS_AUTRE, MEF_CU2$TPS_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU2$TPS_AUTRE, MEF_CU2$TPS_AUTRE)))

t.test(CONF_CU1$TPS_AUTRE, CONF_CU2$TPS_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$TPS_AUTRE, CONF_CU2$TPS_AUTRE, method = "paired")))
t.test(MEF_CU1$TPS_AUTRE, MEF_CU2$TPS_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_CU1$TPS_AUTRE, MEF_CU2$TPS_AUTRE, method = "paired")))
```

################ FRÉQUENCE DES REGARDS

ANOVA ET T-TEST FRÉQUENCE DES REGARDS PÉRIODES
```{r}
FRQ_ROUTE_AOV <- Anova(lm(FRQ_ROUTE~TEMPS*GROUPE, data = PERIODES), type = 2, white.adjust=TRUE)
FRQ_ROUTE_AOV_ST <- anova_stats(Anova(lm(FRQ_ROUTE~TEMPS*GROUPE, data = PERIODES), type = 2))
FRQ_ROUTE_AOV
FRQ_ROUTE_AOV_ST

ggplot(PERIODES_M) + aes(x = TEMPS, y = FRQ_ROUTE, group= GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=FRQ_ROUTE-FRQ_ROUTE_sd, ymax=FRQ_ROUTE+FRQ_ROUTE_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Fréquence des regards vers la route") + 
  labs(x = "Période", y = "Fréquence des regards (%)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_TOT$FRQ_ROUTE, MEF_TOT$FRQ_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_TOT$FRQ_ROUTE, MEF_TOT$FRQ_ROUTE)))
t.test(CONF_P1$FRQ_ROUTE, MEF_P1$FRQ_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$FRQ_ROUTE, MEF_P1$FRQ_ROUTE)))
t.test(CONF_P2$FRQ_ROUTE, MEF_P2$FRQ_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$FRQ_ROUTE, MEF_P2$FRQ_ROUTE)))
t.test(CONF_P3$FRQ_ROUTE, MEF_P3$FRQ_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P3$FRQ_ROUTE, MEF_P3$FRQ_ROUTE)))

t.test(CONF_P1$FRQ_ROUTE, CONF_P2$FRQ_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$FRQ_ROUTE, CONF_P2$FRQ_ROUTE, method = "paired")))
t.test(CONF_P2$FRQ_ROUTE, CONF_P3$FRQ_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$FRQ_ROUTE, CONF_P3$FRQ_ROUTE, method = "paired")))
t.test(MEF_P1$FRQ_ROUTE, MEF_P2$FRQ_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P1$FRQ_ROUTE, MEF_P2$FRQ_ROUTE, method = "paired")))
t.test(MEF_P2$FRQ_ROUTE, MEF_P3$FRQ_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P2$FRQ_ROUTE, MEF_P3$FRQ_ROUTE, method = "paired")))

FRQ_RETRO_AOV <- Anova(lm(FRQ_RETRO~TEMPS*GROUPE, data = PERIODES), type = 2, white.adjust=TRUE)
FRQ_RETRO_AOV_ST <- anova_stats(Anova(lm(FRQ_RETRO~TEMPS*GROUPE, data = PERIODES), type = 2))
FRQ_RETRO_AOV
FRQ_RETRO_AOV_ST

ggplot(PERIODES_M) + aes(x = TEMPS, y = FRQ_RETRO, group= GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=FRQ_RETRO-FRQ_RETRO_sd, ymax=FRQ_RETRO+FRQ_RETRO_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Fréquence des regards vers les rétroviseurs") + 
  labs(x = "Période", y = "Fréquence des regards (%)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_TOT$FRQ_RETRO, MEF_TOT$FRQ_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_TOT$FRQ_RETRO, MEF_TOT$FRQ_RETRO)))
t.test(CONF_P1$FRQ_RETRO, MEF_P1$FRQ_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$FRQ_RETRO, MEF_P1$FRQ_RETRO)))
t.test(CONF_P2$FRQ_RETRO, MEF_P2$FRQ_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$FRQ_RETRO, MEF_P2$FRQ_RETRO)))
t.test(CONF_P3$FRQ_RETRO, MEF_P3$FRQ_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P3$FRQ_RETRO, MEF_P3$FRQ_RETRO)))

t.test(CONF_P1$FRQ_RETRO, CONF_P2$FRQ_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$FRQ_RETRO, CONF_P2$FRQ_RETRO, method = "paired")))
t.test(CONF_P2$FRQ_RETRO, CONF_P3$FRQ_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$FRQ_RETRO, CONF_P3$FRQ_RETRO, method = "paired")))
t.test(MEF_P1$FRQ_RETRO, MEF_P2$FRQ_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P1$FRQ_RETRO, MEF_P2$FRQ_RETRO, method = "paired")))
t.test(MEF_P2$FRQ_RETRO, MEF_P3$FRQ_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P2$FRQ_RETRO, MEF_P3$FRQ_RETRO, method = "paired")))


FRQ_RETRO_ROUTE_AOV <- Anova(lm(FRQ_RETRO_ROUTE~TEMPS*GROUPE, data = PERIODES), type = 2, white.adjust=TRUE)
FRQ_RETRO_ROUTE_AOV_ST <- anova_stats(Anova(lm(FRQ_RETRO_ROUTE~TEMPS*GROUPE, data = PERIODES), type = 2))
FRQ_RETRO_ROUTE_AOV
FRQ_RETRO_ROUTE_AOV_ST

ggplot(PERIODES_M) + 
  geom_line(aes(x = TEMPS, y = FRQ_RETRO_ROUTE, group= GROUPE, col = GROUPE, linetype = "dashed"), position=position_dodge(0.1)) + 
    geom_line(aes(x = TEMPS, y = FRQ_AVB, group= GROUPE, col = GROUPE, linetype = "solid"), position=position_dodge(0.2)) + 
  scale_linetype_discrete(name = "Données", labels = c("Route/Rétro", "AVB")) +
  geom_point(aes(x = TEMPS, y = FRQ_RETRO_ROUTE, group= GROUPE, col = GROUPE), position=position_dodge(0.1)) + geom_point(aes(x = TEMPS, y = FRQ_AVB, group= GROUPE, col = GROUPE), position=position_dodge(0.2)) +
  geom_errorbar(aes(x = TEMPS, y = FRQ_RETRO_ROUTE, group= GROUPE, col = GROUPE, ymin=FRQ_RETRO_ROUTE-FRQ_RETRO_ROUTE_sd, ymax=FRQ_RETRO_ROUTE+FRQ_RETRO_ROUTE_sd), width=0.1, position=position_dodge(0.1)) +
  geom_errorbar(aes(x = TEMPS, y = FRQ_RETRO_ROUTE, group= GROUPE, col = GROUPE, ymin=FRQ_AVB-FRQ_AVB_sd, ymax=FRQ_AVB+FRQ_AVB_sd), width=0.1, position=position_dodge(0.2)) + 
  ggtitle("Fréquence des regards vers la route\n& les rétroviseurs vs vers l'AVB") + 
  labs(x = "Période", y = "Fréquence des regards", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_TOT$FRQ_RETRO_ROUTE, MEF_TOT$FRQ_RETRO_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_TOT$FRQ_RETRO_ROUTE, MEF_TOT$FRQ_RETRO_ROUTE)))
t.test(CONF_P1$FRQ_RETRO_ROUTE, MEF_P1$FRQ_RETRO_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$FRQ_RETRO_ROUTE, MEF_P1$FRQ_RETRO_ROUTE)))
t.test(CONF_P2$FRQ_RETRO_ROUTE, MEF_P2$FRQ_RETRO_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$FRQ_RETRO_ROUTE, MEF_P2$FRQ_RETRO_ROUTE)))
t.test(CONF_P3$FRQ_RETRO_ROUTE, MEF_P3$FRQ_RETRO_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P3$FRQ_RETRO_ROUTE, MEF_P3$FRQ_RETRO_ROUTE)))

t.test(CONF_P1$FRQ_RETRO_ROUTE, CONF_P2$FRQ_RETRO_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$FRQ_RETRO_ROUTE, CONF_P2$FRQ_RETRO_ROUTE, method = "paired")))
t.test(CONF_P2$FRQ_RETRO_ROUTE, CONF_P3$FRQ_RETRO_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$FRQ_RETRO_ROUTE, CONF_P3$FRQ_RETRO_ROUTE, method = "paired")))
t.test(MEF_P1$FRQ_RETRO_ROUTE, MEF_P2$FRQ_RETRO_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P1$FRQ_RETRO_ROUTE, MEF_P2$FRQ_RETRO_ROUTE, method = "paired")))
t.test(MEF_P2$FRQ_RETRO_ROUTE, MEF_P3$FRQ_RETRO_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P2$FRQ_RETRO_ROUTE, MEF_P3$FRQ_RETRO_ROUTE, method = "paired")))



FRQ_AVB_AOV <- Anova(lm(FRQ_AVB~TEMPS*GROUPE, data = PERIODES), type = 2, white.adjust=TRUE)
FRQ_AVB_AOV_ST <- anova_stats(Anova(lm(FRQ_AVB~TEMPS*GROUPE, data = PERIODES), type = 2))
FRQ_AVB_AOV
FRQ_AVB_AOV_ST

ggplot(PERIODES_M) + aes(x = TEMPS, y = FRQ_AVB, group= GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=FRQ_AVB-FRQ_AVB_sd, ymax=FRQ_AVB+FRQ_AVB_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Fréquence des regards vers l'AVB") + 
  labs(x = "Période", y = "Fréquence des regards (%)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_TOT$FRQ_AVB, MEF_TOT$FRQ_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_TOT$FRQ_AVB, MEF_TOT$FRQ_AVB)))
t.test(CONF_P1$FRQ_AVB, MEF_P1$FRQ_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$FRQ_AVB, MEF_P1$FRQ_AVB)))
t.test(CONF_P2$FRQ_AVB, MEF_P2$FRQ_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$FRQ_AVB, MEF_P2$FRQ_AVB)))
t.test(CONF_P3$FRQ_AVB, MEF_P3$FRQ_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P3$FRQ_AVB, MEF_P3$FRQ_AVB)))

t.test(CONF_P1$FRQ_AVB, CONF_P2$FRQ_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$FRQ_AVB, CONF_P2$FRQ_AVB, method = "paired")))
t.test(CONF_P2$FRQ_AVB, CONF_P3$FRQ_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$FRQ_AVB, CONF_P3$FRQ_AVB, method = "paired")))
t.test(MEF_P1$FRQ_AVB, MEF_P2$FRQ_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P1$FRQ_AVB, MEF_P2$FRQ_AVB, method = "paired")))
t.test(MEF_P2$FRQ_AVB, MEF_P3$FRQ_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P2$FRQ_AVB, MEF_P3$FRQ_AVB, method = "paired")))

FRQ_AUTRE_AOV <- Anova(lm(FRQ_AUTRE~TEMPS*GROUPE, data = PERIODES), type = 2, white.adjust=TRUE)
FRQ_AUTRE_AOV_ST <- anova_stats(Anova(lm(FRQ_AUTRE~TEMPS*GROUPE, data = PERIODES), type = 2))
FRQ_AUTRE_AOV
FRQ_AUTRE_AOV_ST

ggplot(PERIODES_M) + aes(x = TEMPS, y = FRQ_AUTRE, group= GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=FRQ_AUTRE-FRQ_AUTRE_sd, ymax=FRQ_AUTRE+FRQ_AUTRE_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Fréquence des regards vers une autre zone") + 
  labs(x = "Période", y = "Fréquence des regards (%)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_TOT$FRQ_AUTRE, MEF_TOT$FRQ_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_TOT$FRQ_AUTRE, MEF_TOT$FRQ_AUTRE)))
t.test(CONF_P1$FRQ_AUTRE, MEF_P1$FRQ_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$FRQ_AUTRE, MEF_P1$FRQ_AUTRE)))
t.test(CONF_P2$FRQ_AUTRE, MEF_P2$FRQ_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$FRQ_AUTRE, MEF_P2$FRQ_AUTRE)))
t.test(CONF_P3$FRQ_AUTRE, MEF_P3$FRQ_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P3$FRQ_AUTRE, MEF_P3$FRQ_AUTRE)))

t.test(CONF_P1$FRQ_AUTRE, CONF_P2$FRQ_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P1$FRQ_AUTRE, CONF_P2$FRQ_AUTRE, method = "paired")))
t.test(CONF_P2$FRQ_AUTRE, CONF_P3$FRQ_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_P2$FRQ_AUTRE, CONF_P3$FRQ_AUTRE, method = "paired")))
t.test(MEF_P1$FRQ_AUTRE, MEF_P2$FRQ_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P1$FRQ_AUTRE, MEF_P2$FRQ_AUTRE, method = "paired")))
t.test(MEF_P2$FRQ_AUTRE, MEF_P3$FRQ_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_P2$FRQ_AUTRE, MEF_P3$FRQ_AUTRE, method = "paired")))
```

ANOVA ET T-TEST REGARDS CU
``` {r}
FRQ_ROUTE_AOV <- Anova(lm(FRQ_ROUTE~TEMPS*GROUPE, data = CU), type = 2, white.adjust=TRUE)
FRQ_ROUTE_AOV_ST <- anova_stats(Anova(lm(FRQ_ROUTE~TEMPS*GROUPE, data = CU), type = 2))
FRQ_ROUTE_AOV
FRQ_ROUTE_AOV_ST

ggplot(CU_M) + aes(x = TEMPS, y = FRQ_ROUTE, group= GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=FRQ_ROUTE-FRQ_ROUTE_sd, ymax=FRQ_ROUTE+FRQ_ROUTE_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Fréquence des regards vers la route") + 
  labs(x = "Cas d'Usage", y = "Fréquence des regards (%)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_CU1$FRQ_ROUTE, MEF_CU1$FRQ_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
t.test(CONF_CU2$FRQ_ROUTE, MEF_CU2$FRQ_ROUTE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)

t.test(CONF_CU1$FRQ_ROUTE, CONF_CU2$FRQ_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
t.test(MEF_CU1$FRQ_ROUTE, MEF_CU2$FRQ_ROUTE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)

FRQ_RETRO_AOV <- Anova(lm(FRQ_RETRO~TEMPS*GROUPE, data = CU), type = 2, white.adjust=TRUE)
FRQ_RETRO_AOV_ST <- anova_stats(Anova(lm(FRQ_RETRO~TEMPS*GROUPE, data = CU), type = 2))
FRQ_RETRO_AOV
FRQ_RETRO_AOV_ST

ggplot(CU_M) + aes(x = TEMPS, y = FRQ_RETRO, group= GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=FRQ_RETRO-FRQ_RETRO_sd, ymax=FRQ_RETRO+FRQ_RETRO_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Fréquence des regards vers les rétroviseurs") + 
  labs(x = "Cas d'Usage", y = "Fréquence des regards (%)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_CU1$FRQ_RETRO, MEF_CU1$FRQ_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$FRQ_RETRO, MEF_CU1$FRQ_RETRO)))
t.test(CONF_CU2$FRQ_RETRO, MEF_CU2$FRQ_RETRO, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU2$FRQ_RETRO, MEF_CU2$FRQ_RETRO)))

t.test(CONF_CU1$FRQ_RETRO, CONF_CU2$FRQ_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$FRQ_RETRO, CONF_CU2$FRQ_RETRO, method = "paired")))
t.test(MEF_CU1$FRQ_RETRO, MEF_CU2$FRQ_RETRO, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_CU1$FRQ_RETRO, MEF_CU2$FRQ_RETRO, method = "paired")))


ggplot(CU_M) + 
  geom_line(aes(x = TEMPS, y = FRQ_RETRO_ROUTE, group= GROUPE, col = GROUPE, linetype = "dashed"), position=position_dodge(0.1)) + 
    geom_line(aes(x = TEMPS, y = FRQ_AVB, group= GROUPE, col = GROUPE, linetype = "solid"), position=position_dodge(0.2)) + 
  scale_linetype_discrete(name = "Données", labels = c("Route/Rétro", "AVB")) +
  geom_point(aes(x = TEMPS, y = FRQ_RETRO_ROUTE, group= GROUPE, col = GROUPE), position=position_dodge(0.1)) + geom_point(aes(x = TEMPS, y = FRQ_AVB, group= GROUPE, col = GROUPE), position=position_dodge(0.2)) +
  geom_errorbar(aes(x = TEMPS, y = FRQ_RETRO_ROUTE, group= GROUPE, col = GROUPE, ymin=FRQ_RETRO_ROUTE-FRQ_RETRO_ROUTE_sd, ymax=FRQ_RETRO_ROUTE+FRQ_RETRO_ROUTE_sd), width=0.1, position=position_dodge(0.1)) +
  geom_errorbar(aes(x = TEMPS, y = FRQ_RETRO_ROUTE, group= GROUPE, col = GROUPE, ymin=FRQ_AVB-FRQ_AVB_sd, ymax=FRQ_AVB+FRQ_AVB_sd), width=0.1, position=position_dodge(0.2)) + 
  ggtitle("Fréquence des regards vers la route\n& les rétroviseurs vs vers l'AVB") + 
  labs(x = "Cas d'Usage", y = "Fréquence des regards", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))


FRQ_AVB_AOV <- Anova(lm(FRQ_AVB~TEMPS*GROUPE, data = CU), type = 2, white.adjust=TRUE)
FRQ_AVB_AOV_ST <- anova_stats(Anova(lm(FRQ_AVB~TEMPS*GROUPE, data = CU), type = 2))
FRQ_AVB_AOV
FRQ_AVB_AOV_ST

ggplot(CU_M) + aes(x = TEMPS, y = FRQ_AVB, group= GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=FRQ_AVB-FRQ_AVB_sd, ymax=FRQ_AVB+FRQ_AVB_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Fréquence des regards vers l'AVB") + 
  labs(x = "Cas d'Usage", y = "Fréquence des regards (%)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_CU1$FRQ_AVB, MEF_CU1$FRQ_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$FRQ_AVB, MEF_CU1$FRQ_AVB)))
t.test(CONF_CU2$FRQ_AVB, MEF_CU2$FRQ_AVB, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU2$FRQ_AVB, MEF_CU2$FRQ_AVB)))

t.test(CONF_CU1$FRQ_AVB, CONF_CU2$FRQ_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$FRQ_AVB, CONF_CU2$FRQ_AVB, method = "paired")))
t.test(MEF_CU1$FRQ_AVB, MEF_CU2$FRQ_AVB, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_CU1$FRQ_AVB, MEF_CU2$FRQ_AVB, method = "paired")))

FRQ_AUTRE_AOV <- Anova(lm(FRQ_AUTRE~TEMPS*GROUPE, data = CU), type = 2, white.adjust=TRUE)
FRQ_AUTRE_AOV_ST <- anova_stats(Anova(lm(FRQ_AUTRE~TEMPS*GROUPE, data = CU), type = 2))
FRQ_AUTRE_AOV
FRQ_AUTRE_AOV_ST

ggplot(CU_M) + aes(x = TEMPS, y = FRQ_AUTRE, group= GROUPE, col = GROUPE, ymin = 0) + geom_line(position=position_dodge(0.1)) + geom_point(position=position_dodge(0.1)) + geom_errorbar(aes(ymin=FRQ_AUTRE-FRQ_AUTRE_sd, ymax=FRQ_AUTRE+FRQ_AUTRE_sd), width=0.1, position=position_dodge(0.1)) + 
  ggtitle("Fréquence des regards vers une autre zone") + 
  labs(x = "Cas d'Usage", y = "Fréquence des regards (%)", col = "Groupe") + 
  theme(plot.title = element_text(hjust = 0.5))

t.test(CONF_CU1$FRQ_AUTRE, MEF_CU1$FRQ_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$FRQ_AUTRE, MEF_CU1$FRQ_AUTRE)))
t.test(CONF_CU2$FRQ_AUTRE, MEF_CU2$FRQ_AUTRE, alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU2$FRQ_AUTRE, MEF_CU2$FRQ_AUTRE)))

t.test(CONF_CU1$FRQ_AUTRE, CONF_CU2$FRQ_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(CONF_CU1$FRQ_AUTRE, CONF_CU2$FRQ_AUTRE, method = "paired")))
t.test(MEF_CU1$FRQ_AUTRE, MEF_CU2$FRQ_AUTRE, alternative = c("two.sided"), paired = TRUE, var.equal = FALSE, conf.level = 0.95)
print(paste("Cohen's d :", cohensD(MEF_CU1$FRQ_AUTRE, MEF_CU2$FRQ_AUTRE, method = "paired")))
```